name: MinecraftPyServer
main: com.macuyiko.minecraftpyserver.MinecraftPyServerPlugin
version: 0.7
commands:
  py:
    description: Execute Python code on Jython interpreter
    usage: /py code
  pyrestart:
    description: Restart Jython interpreter
    usage: /pyrestart
  pyload:
    description: Execute a server-side Python file on Jython interpreter
    usage: /pyload file